# name: Publish Docker

# on:
#   push:
#     branches: [ master ]

# jobs:
#   build:
#     runs-on: ubuntu-last
#     steps:
#       - uses: actions/checkout@master
#       - name: Publish to Registry
#         uses: elgohr/Publish-Docker-Github-Action@master
#         with:
#           registry: docker.pkg.github.com
#           name: docker.pkg.github.com/<username>/<path>
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}
#           tags: 'develop'
